#### 1. Create a NumPy array of shape (5, 5) filled with random integers between 1 and 20. Replace all the elements in the third column with 1.

In [2]:
import numpy as np

In [3]:
arr = np.random.randint(1,21,size=(5,5))
print("Original Array: ",arr)

arr[:,2] = 1
print("modified array")
print(arr)

Original Array:  [[19 12 17  7  6]
 [ 4  9  1 10 19]
 [ 2 14  4  9 13]
 [ 6  4 17  3 10]
 [20 15  2  4 18]]
modified array
[[19 12  1  7  6]
 [ 4  9  1 10 19]
 [ 2 14  1  9 13]
 [ 6  4  1  3 10]
 [20 15  1  4 18]]


#### 2. Create a NumPy array of shape (4, 4) with values from 1 to 16. Replace the diagonal elements with 0.

In [6]:
arr1 = np.arange(1,17).reshape(4,4)
print(arr1)

# Replace diagonal elements with 0 
np.fill_diagonal(arr1,0)
print("Modifed Array")
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Modifed Array
[[ 0  2  3  4]
 [ 5  0  7  8]
 [ 9 10  0 12]
 [13 14 15  0]]


#### 3. Create a NumPy array of shape (6, 6) with values from 1 to 36. Extract the sub-array consisting of the 3rd to 5th rows and 2nd to 4th columns.

In [7]:
arr2 = np.arange(1,37).reshape(6,6)
print("Original array")
print(arr2)

sub_array = arr2[2:5,1:4]
print("Sub-array")
print(sub_array)

Original array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [13 14 15 16 17 18]
 [19 20 21 22 23 24]
 [25 26 27 28 29 30]
 [31 32 33 34 35 36]]
Sub-array
[[14 15 16]
 [20 21 22]
 [26 27 28]]


#### 4. Create a NumPy array of shape (5, 5) with random integers. Extract the elements on the border.

In [3]:
arr3 = np.random.randint(1,21,size=(5,5))
print(arr3)

# Border elements
border_elements = np.concatenate((arr3[0,:],arr3[-1,:],arr3[1:-1,0],arr3[1:-1,-1]))
print("border elements")
print(border_elements)

[[ 8  8 15 11 16]
 [ 3  3 17  3  1]
 [15 16 10  6  2]
 [ 6 10  7 11 19]
 [ 1 11  4  2 13]]
border elements
[ 8  8 15 11 16  1 11  4  2 13  3 15  6  1  2 19]


#### 5. Create two NumPy arrays of shape (3, 4) filled with random integers. Perform element-wise addition, subtraction, multiplication, and division.

In [4]:
array1 = np.random.randint(1,13,size=(3,4))
array2 = np.random.randint(1,13,size=(3,4))

print("Array 1")
print(array1)

print("Array 2")
print(array2)

print("Element wise Addition")
print(array1+array2)

print("Element wise Subtraction")
print(array1-array2)

print("Element wise Multiplication")
print(array1*array2)

print("Element wise Division")
print(array1/array2)

Array 1
[[ 2  6 11  4]
 [ 2  7 10  6]
 [ 3 11 10  3]]
Array 2
[[ 1 12  7  9]
 [ 1  5  7  8]
 [ 6  3 10  8]]
Element wise Addition
[[ 3 18 18 13]
 [ 3 12 17 14]
 [ 9 14 20 11]]
Element wise Subtraction
[[ 1 -6  4 -5]
 [ 1  2  3 -2]
 [-3  8  0 -5]]
Element wise Multiplication
[[  2  72  77  36]
 [  2  35  70  48]
 [ 18  33 100  24]]
Element wise Division
[[2.         0.5        1.57142857 0.44444444]
 [2.         1.4        1.42857143 0.75      ]
 [0.5        3.66666667 1.         0.375     ]]


#### 6. Create a NumPy array of shape (4, 4) with values from 1 to 16. Compute the row-wise and column-wise sum.

In [5]:
arr4 = np.arange(1,17).reshape(4,4)
print(arr4)

row_sum = np.sum(arr4,axis=1)
column_sum = np.sum(arr4,axis=0)

print("Row wise sum")
print(row_sum)

print("Column wise sum")
print(column_sum)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Row wise sum
[10 26 42 58]
Column wise sum
[28 32 36 40]


#### 7. Create a NumPy array of shape (5, 5) filled with random integers. Compute the mean, median, standard deviation, and variance of the array.

In [6]:
arr5 = np.random.randint(1,26,size=(5,5))

mean = np.mean(arr5)
median = np.median(arr5)
standard_deviation = np.std(arr5)
variance = np.var(arr5)

print("Mean : ",mean)
print("Median : ",median)
print("Standard deviation : ",standard_deviation)
print("Variance : ",variance)

Mean :  11.68
Median :  12.0
Standard deviation :  5.876869915184443
Variance :  34.537600000000005


#### 8. Create a NumPy array of shape (3, 3) with values from 1 to 9. Normalize the array (i.e., scale the values to have a mean of 0 and a standard deviation of 1).

In [7]:
arr6 = np.arange(1,10).reshape(3,3)

mean = np.mean(arr6)
std = np.std(arr6)

normalized_array = (arr6 - mean) / std
print("Normalized Array ")
print(normalized_array)

Normalized Array 
[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


#### 9. Create a NumPy array of shape (3, 3) filled with random integers. Add a 1D array of shape (3,) to each row of the 2D array using broadcasting.

In [8]:
d3_arr = np.random.randint(1,10,size=(3,3))
print("3 dimension array ")
print(d3_arr)

d1_arr = np.random.randint(1,4,size=(3,))
print("1 dimension array ")
print(d1_arr)

result = d3_arr + d1_arr
print("Result")
print(result)

3 dimension array 
[[7 6 2]
 [2 8 7]
 [5 9 4]]
1 dimension array 
[1 1 1]
Result
[[ 8  7  3]
 [ 3  9  8]
 [ 6 10  5]]


#### 10. Create a NumPy array of shape (4, 4) filled with random integers. Subtract a 1D array of shape (4,) from each column of the 2D array using broadcasting.

In [11]:
array = np.random.randint(1, 11, size=(4, 4))
column_array = np.random.randint(1, 11, size=(4,))
print("Original array:")
print(array)
print("1D array:")
print(column_array)

# Subtract the 1D array from each column of the 2D array using broadcasting
result = array - column_array[:, np.newaxis]
print("Resulting array:")
print(result)

Original array:
[[ 3 10  6  1]
 [ 5  8  7  6]
 [ 8  1  4  2]
 [ 6  1  7  7]]
1D array:
[10  5  4  8]
Resulting array:
[[-7  0 -4 -9]
 [ 0  3  2  1]
 [ 4 -3  0 -2]
 [-2 -7 -1 -1]]


#### 11. Create a NumPy array of shape (3, 3) representing a matrix. Compute its determinant, inverse, and eigenvalues.

In [3]:
arr7 = np.random.randint(1,11,size=(3,3))
print("Original matrix")
print(arr7)

determinant = np.linalg.det(arr7)
inverse = np.linalg.inv(arr7)
eigenalues = np.linalg.eigvals(arr7)

print("Dterminant : ",determinant)
print("Inverse : ",inverse)
print("Eigen values : ",eigenalues)

Original matrix
[[ 2  6  4]
 [ 9  8  2]
 [ 4  7 10]]
Dterminant :  -235.9999999999999
Inverse :  [[-0.27966102  0.13559322  0.08474576]
 [ 0.34745763 -0.01694915 -0.13559322]
 [-0.13135593 -0.04237288  0.16101695]]
Eigen values :  [17.37690699 -2.60015357  5.22324657]


#### 12. Create two NumPy arrays of shape (2, 3) and (3, 2). Perform matrix multiplication on these arrays.

In [5]:
arr1 = np.random.randint(1,7,size=(2,3))
arr2 = np.random.randint(1,7,size=(3,2))

print("Array 1 : ",arr1)
print("Array 2 : ",arr2)

result = np.dot(arr1,arr2)
print("Result : ",result)

Array 1 :  [[3 5 6]
 [5 1 1]]
Array 2 :  [[5 6]
 [6 4]
 [4 2]]
Result :  [[69 50]
 [35 36]]


#### 13. Create a NumPy array of shape (3, 3) with values from 1 to 9. Reshape the array to shape (1, 9) and then to shape (9, 1).

In [6]:
arr1 = np.arange(1,10).reshape(3,3)
print("Original array : ",arr1)

reshaped_arr_1 = arr1.reshape(1,9)
print("Reshaped array of (1,9) is : ",reshaped_arr_1)

reshaped_arr_2 = arr1.reshape(9,1)
print("Reshaped array of (9,1) is : ",reshaped_arr_2)

Original array :  [[1 2 3]
 [4 5 6]
 [7 8 9]]
Reshaped array of (1,9) is :  [[1 2 3 4 5 6 7 8 9]]
Reshaped array of (9,1) is :  [[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


#### 14. Create a NumPy array of shape (5, 5) filled with random integers. Flatten the array and then reshape it back to (5, 5).

In [7]:
arr1 = np.random.randint(1,26,size=(5,5))
print("Original array : ",arr1)

flatten_array = arr1.flatten()
print("Flattened array : ",flatten_array)

reshaped_1 = flatten_array.reshape(5,5)
print(reshaped_1)

Original array :  [[19  5  1  8 15]
 [ 4 14  5 22 22]
 [ 3  8  5  3 11]
 [20 10  5  3 25]
 [25 13 21 16  6]]
Flattened array :  [19  5  1  8 15  4 14  5 22 22  3  8  5  3 11 20 10  5  3 25 25 13 21 16
  6]
[[19  5  1  8 15]
 [ 4 14  5 22 22]
 [ 3  8  5  3 11]
 [20 10  5  3 25]
 [25 13 21 16  6]]


#### 15. Create a NumPy array of shape (5, 5) filled with random integers. Use fancy indexing to extract the elements at the corners of the array.

In [8]:
arr1 = np.random.randint(1,10,size=(5,5))
print("Array : ",arr1)

corners = arr1[[0,0,-1,-1],[0,-1,0,-1]]
print("Corner elements")
print(corners)

Array :  [[6 1 8 4 3]
 [6 5 8 8 2]
 [7 2 3 6 1]
 [3 7 9 3 4]
 [4 5 3 6 4]]
Corner elements
[6 3 4 4]


#### 16. Create a NumPy array of shape (4, 4) filled with random integers. Use boolean indexing to set all elements greater than 10 to 10.

In [10]:
arr1 = np.random.randint(1,20,size=(4,4))
print("Original array : ",arr1)

arr1[arr1 > 10] = 10
print("Modified array ")
print(arr1)

Original array :  [[14  7  2 14]
 [12 15  2 16]
 [ 3  2  1 13]
 [ 7  6  1 14]]
Modified array 
[[10  7  2 10]
 [10 10  2 10]
 [ 3  2  1 10]
 [ 7  6  1 10]]


#### 17. Create a structured array with fields 'name' (string), 'age' (integer), and 'weight' (float). Add some data and sort the array by age.

In [3]:
data_type = [('name','U10'),('age','i4'),('weight','f4')]
data = np.array([
    ('Prem',21,45.5),
    ('Karnav',20,55.2),
    ('Krish',21,60.5)
],dtype=data_type)

print("Original data")
print(data)

sorted_data = np.sort(data,order='age')
print("Sorted data by age")
print(sorted_data)

Original data
[('Prem', 21, 45.5) ('Karnav', 20, 55.2) ('Krish', 21, 60.5)]
Sorted data by age
[('Karnav', 20, 55.2) ('Krish', 21, 60.5) ('Prem', 21, 45.5)]


#### 18. Create a structured array with fields 'x' and 'y' (both integers). Add some data and compute the Euclidean distance between each pair of points.

In [4]:
# Create a structured array with fields 'x' and 'y'
data_type = [('x', 'i4'), ('y', 'i4')]
data = np.array([(1, 2), (3, 4), (5, 6)], dtype=data_type)
print("Original array:")
print(data)

# Compute the Euclidean distance between each pair of points
distances = np.sqrt((data['x'][:, np.newaxis] - data['x'])**2 + (data['y'][:, np.newaxis] - data['y'])**2)
print("Euclidean distances:")
print(distances)

Original array:
[(1, 2) (3, 4) (5, 6)]
Euclidean distances:
[[0.         2.82842712 5.65685425]
 [2.82842712 0.         2.82842712]
 [5.65685425 2.82842712 0.        ]]


#### 19. Create a masked array of shape (4, 4) with random integers and mask the elements greater than 10. Compute the sum of the unmasked elements.

In [5]:
import numpy.ma as ma

arr1 = np.random.randint(1,17,size=(4,4))
masked = ma.masked_greater(arr1,10)

print("Original array")
print(arr1)
print("Masked Array")
print(masked)

unmaksed_sum = masked.sum()
print("Sum of unmasked array : ",unmaksed_sum)

Original array
[[12  6  8  5]
 [ 6 11 12 11]
 [ 5 14  9  5]
 [14  9 13  6]]
Masked Array
[[-- 6 8 5]
 [6 -- -- --]
 [5 -- 9 5]
 [-- 9 -- 6]]
Sum of unmasked array :  59


#### 20. Create a masked array of shape (3, 3) with random integers and mask the diagonal elements. Replace the masked elements with the mean of the unmasked elements.

In [7]:
import numpy.ma as ma

arr1 = np.random.randint(1,10,size=(3,3))
masked = ma.masked_array(arr1 , mask=np.eye(3,dtype=bool))

print("Original array")
print(arr1)
print("Masked array")
print(masked)

unmasked_mean = masked.mean()
masked = masked.filled(unmasked_mean)
print("Modified masked array")
print(masked)

Original array
[[1 3 6]
 [8 7 9]
 [7 6 1]]
Masked array
[[-- 3 6]
 [8 -- 9]
 [7 6 --]]
Modified masked array
[[6 3 6]
 [8 6 9]
 [7 6 6]]
